include:
  - board: seeeduino_xiao_ble
    shield: kimiboard rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
      -DZMK_EXTRA_MODULES="${{ github.workspace }};${{ github.workspace }}/modules/zmk-pmw3610-driver"
      -DCONFIG_PMW3610=y
  - board: seeeduino_xiao_ble
    shield: settings_reset
