include:
  - board: seeeduino_xiao_ble
    shield: kimiboard rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DZMK_EXTRA_MODULES=modules/zmk-pmw3610-driver
  - board: seeeduino_xiao_ble
    shield: settings_reset
